"""Публичный пакет библиотеки pyis74.

Модуль экспортирует основные клиенты, исключения и низкоуровневые типы, которые нужны
пользователям библиотеки.
"""

from importlib.metadata import PackageNotFoundError, version

from pyis74.client import IS74, IS74Async
from pyis74.endpoints import BaseUrl, IS74ServiceUrls
from pyis74.exceptions import (
    IS74APIError,
    IS74AuthError,
    IS74AuthRequiredError,
    IS74Error,
    IS74HTTPError,
    IS74RateLimitError,
    IS74TransportError,
)
from pyis74.models import (
    AccountSummary,
    Address,
    AddressCandidate,
    Balance,
    Camera,
    CameraAccess,
    CameraAccessStatus,
    CameraArchive,
    CameraCoordinates,
    CameraGroup,
    CameraGroupContent,
    CameraHlsLive,
    CameraHlsMedia,
    CameraLimitedInfo,
    CameraMedia,
    CameraMseMedia,
    CameraPosition,
    CameraRealtimeWs,
    CameraSnapshot,
    CameraSnapshotLive,
    CameraSnapshotMedia,
    CameraStreams,
    CameraSupportedFeatures,
    CameraVaFeatures,
    DomofonLinks,
    DomofonOpener,
    DomofonOpenResult,
    DomofonQrOptions,
    DomofonQrValue,
    DomofonRelay,
    DomofonRelayCameras,
    HistoryEvent,
    HistoryEventKind,
    HistoryEventParams,
    HistoryResponse,
    LkToken,
    MobileToken,
    NextPayment,
    PhoneConfirmationCheck,
    PhoneConfirmationStart,
    SelfCameraGroup,
    ServiceStatus,
    UserInfo,
)
from pyis74.options import ClientRequestOptions
from pyis74.transport import IS74Transport, RequestOptions
from pyis74.types import JsonObject, JsonValue

try:
    __version__ = version("pyis74")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = (
    "IS74",
    "AccountSummary",
    "Address",
    "AddressCandidate",
    "Balance",
    "BaseUrl",
    "Camera",
    "CameraAccess",
    "CameraAccessStatus",
    "CameraArchive",
    "CameraCoordinates",
    "CameraGroup",
    "CameraGroupContent",
    "CameraHlsLive",
    "CameraHlsMedia",
    "CameraLimitedInfo",
    "CameraMedia",
    "CameraMseMedia",
    "CameraPosition",
    "CameraRealtimeWs",
    "CameraSnapshot",
    "CameraSnapshotLive",
    "CameraSnapshotMedia",
    "CameraStreams",
    "CameraSupportedFeatures",
    "CameraVaFeatures",
    "ClientRequestOptions",
    "DomofonLinks",
    "DomofonOpenResult",
    "DomofonOpener",
    "DomofonQrOptions",
    "DomofonQrValue",
    "DomofonRelay",
    "DomofonRelayCameras",
    "HistoryEvent",
    "HistoryEventKind",
    "HistoryEventParams",
    "HistoryResponse",
    "IS74APIError",
    "IS74Async",
    "IS74AuthError",
    "IS74AuthRequiredError",
    "IS74Error",
    "IS74HTTPError",
    "IS74RateLimitError",
    "IS74ServiceUrls",
    "IS74Transport",
    "IS74TransportError",
    "JsonObject",
    "JsonValue",
    "LkToken",
    "MobileToken",
    "NextPayment",
    "PhoneConfirmationCheck",
    "PhoneConfirmationStart",
    "RequestOptions",
    "SelfCameraGroup",
    "ServiceStatus",
    "UserInfo",
    "__version__",
)
